name: CICD BopApp
run-name: running by ${{ github.actor }}
on:
  push:
    branches:
      - feature/**
      - bugfix/**
      - main
  pull_request:
    branches:
      - main
jobs:
  Build-And-Deploy-BobApp-Front:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: front/package-lock.json
      - name: list tools version
        run: |
          node -v
          npm -v
      - name: install dependencies
        run: |
          cd front
          npm install
      - name: run tests
        run: |
          cd front
          npm run test
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: front/test-results/junit-report.xml
      - name: test reporting
        uses: dorny/test-reporter@v1
        with:
          name: jasmine test reporting
          path: front/test-results/junit-report.xml
          reporter: jest-junit
      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: push the docker image to docker hub
        uses: docker/build-push-action@v4
        with:
          context: ./front
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/bopapp-front:latest
