name: CICD BopApp on prod env
run-name: running by ${{ github.actor }}
on:
  push:
    branches:
      - main
jobs:
  Build-And-Deploy-BobApp-Back:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '11'
          cache: 'maven'
      - name: list tools version
        run: |
          mvn -v
          java -version
      - name: build app
        run: |
          cd back
          ls -la
          mvn -B -f pom.xml clean package -DskipTests
          ls target
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
