name: CICD BopApp on dev env
run-name: running by ${{ github.actor }}
on:
  push:
    branches:
      - feature/**
      - bugfix/**
  pull_request:
    branches:
      - main
jobs:
  Build-And-Deploy-BobApp-Back:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '11'
          cache: 'maven'
      - name: list tools version
        run: |
          mvn -v
          java -version
      - name: build app
        run: |
          cd back
          mvn -B -f pom.xml clean package -DskipTests
